// JavaScript Document
$('#text-truot').owlCarousel({
    loop:true,
    margin:30,
    nav:false,
	dots:false,
	autoplay:true,
	autoplayTimeout:4000,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:3
        },
        1000:{
            items:4
        }
    }
})
